### ISSUE TITLE
could not update auth token?

### ISSUE THREAD

**Issue by Bulmer** [timiscoding/TelstraSmsApiBashScript#2]
Im getting this error:
"Server took too long to respond. Could not update auth token. Script will now quit. Press ENTER to continue." Which, by looking at the code means a token wasn't found. I have created a file called "keys", placed it in the same directory as the script and put the Consumer Key on the first line and the Consumer Secret on the second line. Have I done anything wrong here, or is this script redundant due to a recent API upgrade?

**Comment by timiscoding** [comment]
What output do you get if you run this in terminal?

`curl --connect-timeout 5 -m 5 -s "https://api.telstra.com/v1/oauth/token?client_id=$APP_KEY&client_secret=$APP_SECRET&grant_type=client_credentials&scope=SMS"`

where $APP_KEY and $APP_SECRET are your consumer key and consumer secret

**Comment by Bulmer** [comment]
I am working with two environments. Within my Linux Laptop environment it returns an access token. In my Linino (arduino yun) environment it returns nothing. Obviously there is a package missing in my Linino setup. Curl is working ok..

**Comment by Bulmer** [comment]
ok, it looks like it was a ssl certificate problem on my end. Thanks for your help anyway. Cheers.

**Comment by timiscoding** [comment]
Thanks for the update. Good to know.
